#!/bin/bash
# 05-django-config.sh — render supervisor + nginx + per-host Django settings.
# Idempotent: re-running overwrites with current template values.
set -euo pipefail

source "${BBL_HOST_CONF:-/etc/bbl-ch-host.conf}"

: "${BBL_HOSTNAME:?BBL_HOSTNAME not set}"
: "${BBL_DB_HOST:?BBL_DB_HOST not set in host.conf}"
: "${BBL_DB_NAME:?BBL_DB_NAME not set in host.conf}"
: "${BBL_DB_USER:?BBL_DB_USER not set in host.conf}"
: "${BBL_DB_PASSWORD:?BBL_DB_PASSWORD not set in host.conf}"
: "${BBL_DJANGO_SECRET_KEY:?BBL_DJANGO_SECRET_KEY not set in host.conf}"

# Defaults that can be overridden in host.conf
BBL_GUNICORN_BIND="${BBL_GUNICORN_BIND:-127.0.0.1:8001}"
BBL_GUNICORN_WORKERS="${BBL_GUNICORN_WORKERS:-9}"
BBL_RUN_BEAT="${BBL_RUN_BEAT:-false}"   # SAFE DEFAULT: no beat; flip to true later
BBL_DOMAIN_ALIASES="${BBL_DOMAIN_ALIASES:-}"

DJANGO_DIR=/projects/bbl-django
TPL=/usr/src/bbl-ch-build/templates  # same path bootstrap.sh clones to

# ── Critical /projects/bbl symlink ──────────────────────────────────
# Many BBL configs / cron jobs / nginx blocks reference /projects/bbl as
# the project root, but the real code now lives at /projects/bbl-django.
# A symlink keeps both paths working without rewriting every reference.
if [[ ! -L /projects/bbl ]]; then
    if [[ -e /projects/bbl ]]; then
        echo "$0: /projects/bbl exists and isn't a symlink — refusing to overwrite" >&2
        exit 1
    fi
    ln -s /projects/bbl-django /projects/bbl
    echo "==> Created /projects/bbl → /projects/bbl-django symlink"
fi

# Ensure bbl user exists (gunicorn + celery run as this user per supervisor templates)
if ! id bbl >/dev/null 2>&1; then
    useradd --system --shell /bin/bash --home /projects/bbl-django bbl
    echo "==> Created bbl user"
fi
chown -R bbl:bbl "$DJANGO_DIR"

# ── Log directories ─────────────────────────────────────────────────
mkdir -p /var/log/supervisor

# Django LOGGING config (in atl_settings.py) expects /var/log/bbl/{accounts,
# general,requests}.log. Without the dir, app boot fails with
# "ValueError: Unable to configure handler 'accounts_log_file'".
mkdir -p /var/log/bbl
chown bbl:bbl /var/log/bbl
chmod 0775 /var/log/bbl

# ── Supervisor configs ──────────────────────────────────────────────

if [[ "$BBL_RUN_BEAT" == "true" ]]; then
    BBL_CELERY_BEAT_FLAG="-B"
    echo "==> celery beat ENABLED on this host (BBL_RUN_BEAT=true)"
else
    BBL_CELERY_BEAT_FLAG=""
    echo "==> celery beat DISABLED on this host (BBL_RUN_BEAT=false). Flip via host.conf + re-run step or edit /etc/supervisor/conf.d/celery.conf manually."
fi

sed -e "s|__BBL_GUNICORN_BIND__|$BBL_GUNICORN_BIND|g" \
    -e "s|__BBL_GUNICORN_WORKERS__|$BBL_GUNICORN_WORKERS|g" \
    "$TPL/bbl-supervisor.conf.template" > /etc/supervisor/conf.d/bbl.conf

sed -e "s|__BBL_CELERY_BEAT_FLAG__|$BBL_CELERY_BEAT_FLAG|g" \
    "$TPL/celery-supervisor.conf.template" > /etc/supervisor/conf.d/celery.conf

echo "==> Wrote /etc/supervisor/conf.d/{bbl,celery}.conf"

# ── nginx site ──────────────────────────────────────────────────────
sed -e "s|__BBL_HOSTNAME__|$BBL_HOSTNAME|g" \
    -e "s|__BBL_DOMAIN_ALIASES__|$BBL_DOMAIN_ALIASES|g" \
    "$TPL/nginx-bbl-site.template" > /etc/nginx/sites-available/bbl

# Enable site (idempotent: ln -sfn replaces existing symlink)
ln -sfn /etc/nginx/sites-available/bbl /etc/nginx/sites-enabled/bbl
rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

nginx -t
systemctl reload nginx
echo "==> nginx site enabled + reloaded"

# ── Per-host Django settings ────────────────────────────────────────
# bbl/settings.py dispatches to <hostname>.py if present, else falls back
# to atl_settings.py for ch-atl* hostnames. Easiest to provide overrides
# via the per-hostname file so we don't fork atl_settings.py.
HOST_SETTINGS="$DJANGO_DIR/bbl/${BBL_HOSTNAME}.py"
cat > "$HOST_SETTINGS" <<PYSETTINGS
"""Auto-generated by bbl-ch-build step 05 at $(date -u +%Y-%m-%dT%H:%M:%SZ).
Per-host overrides on top of bbl.settings dispatcher (which loads
atl_settings.py for ch-atl* hostnames first; then this file applies)."""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "$BBL_DB_NAME",
        "USER": "$BBL_DB_USER",
        "PASSWORD": "$BBL_DB_PASSWORD",
        "HOST": "$BBL_DB_HOST",
        "PORT": "${BBL_DB_PORT:-5432}",
    }
}
SECRET_KEY = "$BBL_DJANGO_SECRET_KEY"
PYSETTINGS

# Optional secrets — append only if set in host.conf
[[ -n "${BBL_REDIS_URL:-}" ]] && echo "REDIS_URL = '$BBL_REDIS_URL'" >> "$HOST_SETTINGS"
[[ -n "${BBL_STRIPE_SECRET_KEY:-}" ]] && echo "STRIPE_SECRET_KEY = '$BBL_STRIPE_SECRET_KEY'" >> "$HOST_SETTINGS"
[[ -n "${BBL_STRIPE_PUBLIC_KEY:-}" ]] && echo "STRIPE_PUBLIC_KEY = '$BBL_STRIPE_PUBLIC_KEY'" >> "$HOST_SETTINGS"
[[ -n "${BBL_STRIPE_WEBHOOK_SECRET:-}" ]] && echo "STRIPE_WEBHOOK_SECRET = '$BBL_STRIPE_WEBHOOK_SECRET'" >> "$HOST_SETTINGS"
[[ -n "${BBL_MAILGUN_API_KEY:-}" ]] && echo "MAILGUN_API_KEY = '$BBL_MAILGUN_API_KEY'" >> "$HOST_SETTINGS"
[[ -n "${BBL_MAILGUN_DOMAIN:-}" ]] && echo "MAILGUN_DOMAIN = '$BBL_MAILGUN_DOMAIN'" >> "$HOST_SETTINGS"
[[ -n "${BBL_TELNYX_USER:-}" ]] && echo "TELNYX_USER = '$BBL_TELNYX_USER'" >> "$HOST_SETTINGS"
[[ -n "${BBL_TELNYX_TOKEN:-}" ]] && echo "TELNYX_TOKEN = '$BBL_TELNYX_TOKEN'" >> "$HOST_SETTINGS"
[[ -n "${BBL_BUGCATCHER_DSN:-}" ]] && echo "BUGCATCHER_DSN = '$BBL_BUGCATCHER_DSN'" >> "$HOST_SETTINGS"

chmod 600 "$HOST_SETTINGS"
chown bbl:bbl "$HOST_SETTINGS"

# Sanity: Django can load + see DATABASES
sudo -u bbl /projects/bbl_env_py3/bin/python "$DJANGO_DIR/manage.py" check 2>&1 | tail -5

echo "==> 05-django-config complete"
