#!/bin/bash
# 05-django-config.sh — render Django settings, supervisor confs, nginx site.
# TODO: this stub captures intent; the substitution and rendering still
# needs to be fleshed out against actual ch-atl1 templates as reference.
set -euo pipefail

source "${BBL_HOST_CONF:-/etc/bbl-build-ch-host.conf}"

: "${BBL_HOSTNAME:?BBL_HOSTNAME not set}"
: "${BBL_DB_HOST:?BBL_DB_HOST not set in host.conf}"
: "${BBL_DB_NAME:?BBL_DB_NAME not set in host.conf}"
: "${BBL_DB_USER:?BBL_DB_USER not set in host.conf}"
: "${BBL_DB_PASSWORD:?BBL_DB_PASSWORD not set in host.conf}"

DJANGO_DIR=/projects/bbl-django
VENV_DIR=/projects/bbl_env_py3

# ── Per-host Django settings file ───────────────────────────────────
# bbl/settings.py loads bbl/<hostname>.py if present (the dispatcher pattern).
# For ch-atl3.bblapp.io that means /projects/bbl-django/bbl/ch-atl3.bblapp.io.py
# OR (if hostname matches) the ch-atl branch of the dispatcher. Confirm
# with the actual settings.py dispatch logic on chb-atl before relying on
# either path.
#
# Easiest path: copy ch-atl1's /projects/bbl-django/bbl/atl_settings.py
# (the prod dispatch target) and override only DATABASES + secrets here.
HOST_SETTINGS="$DJANGO_DIR/bbl/${BBL_HOSTNAME}.py"

cat > "$HOST_SETTINGS" <<PYSETTINGS
"""Auto-generated by bbl-build-ch step 05 at $(date -u +%Y-%m-%dT%H:%M:%SZ)."""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "$BBL_DB_NAME",
        "USER": "$BBL_DB_USER",
        "PASSWORD": "$BBL_DB_PASSWORD",
        "HOST": "$BBL_DB_HOST",
        "PORT": "$BBL_DB_PORT",
    }
}
SECRET_KEY = "$BBL_DJANGO_SECRET_KEY"
# TODO: STRIPE_*, MAILGUN_*, TELNYX_*, BUGCATCHER_DSN, REDIS, etc.
# Reference: ch-atl1's atl_settings.py + chb_settings.py.
PYSETTINGS
chmod 600 "$HOST_SETTINGS"

# ── Supervisor configs ──────────────────────────────────────────────
# TODO: render bbl.conf and celery.conf based on ch-atl1 templates.
# Important: celery.conf MUST include `-B` (embedded beat) ONLY on the
# host that should run scheduled tasks. With a hot-standby pair,
# only ONE of {ch-atl1, ch-atl3} should run beat. Default the new box
# to NOT have -B so we don't double-fire scheduled tasks during ramp.
# Operator flips beat after the cutover is done.

# ── nginx site config ───────────────────────────────────────────────
# TODO: render /etc/nginx/sites-available/bbl pointing at:
#   - upstream gunicorn 127.0.0.1:8001
#   - alias /app → /opt/bblfrontend/build
#   - alias /staticfiles → /projects/bbl-django/staticfiles
# Reference: ch-atl1's /etc/nginx/sites-enabled/bbl (chb-atl differs only in domain).

echo "==> 05-django-config: STUB — see TODOs above before relying on this for prod"
