#!/bin/bash
# 06-cert.sh — Let's Encrypt cert issuance (opt-in for Django boxes).
#
# DEFAULT: skipped. The standard ch-atlN deployment sits behind lb-atl
# which terminates TLS, so this host has no need for its own cert. Only
# opt in (BBL_SKIP_CERT=false in host.conf) when the box is going to
# serve customer HTTPS directly.
#
# Body of this script is still bbl-fs-build's WSS-cert flow (acme.sh +
# chown freeswitch:freeswitch + fs_cli reload hook). It will FAIL on a
# Django box because there is no `freeswitch` user. Needs a Django-shaped
# rewrite (nginx-reload hook, www-data ownership) before BBL_SKIP_CERT=false
# is actually usable on a ch-atlN host. Burned ch-atl7 here 2026-05-05.
set -euo pipefail

# shellcheck disable=SC1091
. "$BBL_HOST_CONF"

if [[ "${BBL_SKIP_CERT:-true}" == "true" ]]; then
    echo "==> Skipping cert (BBL_SKIP_CERT defaults to true for Django boxes; set =false to opt in)"
    exit 0
fi

CRT_DOMAIN="$BBL_DOMAIN"
CRT_EMAIL="${BBL_CERT_EMAIL:-admin@$BBL_DOMAIN}"

if [[ ! -d /etc/acme ]]; then
    echo "==> Installing acme.sh"
    apt-get install -y -q socat
    git clone --quiet https://github.com/acmesh-official/acme.sh.git /usr/src/acme
    # acme.sh's installer uses CWD-relative `cp acme.sh ...` internally,
    # so cd into the checkout before running --install or it fails with
    # 'cp: cannot stat acme.sh: No such file or directory'.
    (cd /usr/src/acme && ./acme.sh --install --home /etc/acme --accountemail "$CRT_EMAIL" >/dev/null)
fi

# Reload hook: assemble wss.pem from the renewed material, reload sofia
cat > /etc/acme/freeswitch-wss.sh <<EOF
#!/bin/bash
# Auto-generated by bbl-fs-build/04-cert.sh — DO NOT EDIT BY HAND
set -euo pipefail
cat /etc/acme/${CRT_DOMAIN}_ecc/${CRT_DOMAIN}.key /etc/acme/${CRT_DOMAIN}_ecc/fullchain.cer \
    > /etc/freeswitch/tls/wss.pem
chown freeswitch:freeswitch /etc/freeswitch/tls/wss.pem
chmod 640 /etc/freeswitch/tls/wss.pem
fs_cli -x 'sofia profile client restart reloadxml'
EOF
chmod 755 /etc/acme/freeswitch-wss.sh

# Source acme env so our PATH includes its tooling
# shellcheck disable=SC1091
. /etc/acme/acme.sh.env

echo "==> Issuing cert for $CRT_DOMAIN (acme.sh --standalone, port 80 must be reachable)"
mkdir -p /etc/freeswitch/tls
chown freeswitch:freeswitch /etc/freeswitch/tls

# --keylength ec-256 → ECDSA (smaller, faster, modern). Falls back to
# rsa if your hosting provider's network has issues; uncomment one only.
/etc/acme/acme.sh --issue \
    --accountemail "$CRT_EMAIL" \
    --standalone \
    --keylength ec-256 \
    -d "$CRT_DOMAIN" \
    || { echo "$0: cert issuance failed — see /etc/acme/acme.sh.log" >&2; exit 1; }

# Install + register the renewal hook so wss.pem stays in sync
/etc/acme/acme.sh --install-cert \
    --domain "$CRT_DOMAIN" \
    --ecc \
    --cert-file /etc/freeswitch/tls/${CRT_DOMAIN}.cert.pem \
    --key-file  /etc/freeswitch/tls/${CRT_DOMAIN}.key.pem \
    --fullchain-file /etc/freeswitch/tls/${CRT_DOMAIN}.fullchain.pem \
    --reloadcmd /etc/acme/freeswitch-wss.sh

echo "==> 04-cert.sh complete (acme.sh's own cron renews automatically)"
